### ISSUE TITLE
Guys, can anyone look at and say what is the solution of this problem? Generative-Art-Opensource-v4 

### ISSUE THREAD

**Issue by doganssen** [HashLips/generative-art-opensource#103]
I adapted generative-art-opensource-v4 to my NFT project. I faced an error. I added config and index files, also screenshot of error. If you solve this problem, I will be grateful.
[config.txt](https://github.com/HashLips/generative-art-opensource/files/7142978/config.txt)
[index.txt](https://github.com/HashLips/generative-art-opensource/files/7142979/index.txt)
![Error](https://user-images.githubusercontent.com/90317010/132836030-a3b30b39-2e62-46b4-95da-eb062aacef1e.PNG)

**Comment by AlfieDarko** [comment]
Looks like your system / files you added node js version needs to match the same as the projects one.

**Comment by doganssen** [comment]
So, what shoul I do?
