### ISSUE TITLE
Rarity generation

### ISSUE THREAD

**Issue by EvilShaggz** [HashLips/generative-art-opensource#11]
Is there a way to only pull one rare or super rare image from a random layer when compiling a rare or super rare image?

**Comment by caiaga** [comment]
@EvilShaggz you mean that for a rare or super rare you would only get one part of the actual rare content and everything else remains the 'original'?
Currently this doesn't work. You can add images of your originals into the rare/super rare folder which allows this permutation to occur, but doesn't give you a guarantee that exactly one rare element will be added (or any for that matter). 
But something that can certainly be introduced with appropriate code adjustments.

**Comment by EvilShaggz** [comment]
I was thinking some sort of function like 
Adding an element id number 1-7 as i have 7 layers
Const raritylayer (raritylayer=(Get rarity)If rarity = rare,super rare get randnum (elementrange) else exit
But i assume this will meant modifying how the image is built also

Ps I literally started looking at code yesterday so please for give lack of knowledge

**Comment by caiaga** [comment]
@EvilShaggz I personally think that would be a little bit inflexible, but not sure what @HashLips thinks about that. Generally though I think this overlaps with what was asked in https://github.com/HashLips/generative-art-opensource/issues/12 and I think that this would be a better and more generic approach. I'm currently looking into this.

**Comment by EvilShaggz** [comment]
Thank you very much for the reply and guiding me to the branches that have this in them you're a legend
