### ISSUE TITLE
Keep getting: TypeError: Cannot read property 'layers' of undefined on V4..

### ISSUE THREAD

**Issue by tobeliten** [HashLips/generative-art-opensource#128]
![image](https://user-images.githubusercontent.com/90567552/133002559-f5ff92ad-f19b-4a6e-8492-e688bc00a132.png)

i think the problem lies within the config.js file. Its probably hard for you to try to figure out the issue without seeing the code, but if anyone else have had the same problem or have an idea of what it could be i would be very gratefull :)

**Comment by Murtagh300** [comment]
how did you fix this ?
