### ISSUE TITLE
Removing blank(empty) traits from metadata

### ISSUE THREAD

**Issue by SDM-Shroom** [HashLips/generative-art-opensource#155]
Hi there,

I was wondering how I can remove blank(empty) traits from metadata.

In my NFT collection, each character has accessories and also ​empty trait (e.g. No eyewear.png)
When combinations with empty trait is created, metadata also contains ​empty trait (No eyewear) as propatiy.

Do yo guys know how can I remove only empty traits from metadata?

Thanks,

<img width="373" alt="Screen Shot 2021-09-18 at 15 49 41" src="https://user-images.githubusercontent.com/90505831/133879364-4981ef80-d6a7-403d-8f97-1b67c061e555.png">

**Comment by SDM-Shroom** [comment]
forgot to mention, I'm using generative art opensource (v4)

**Comment by Judd515** [comment]
@SDM-Shroom, were you able to resolve this?

**Comment by s-d-sd** [comment]
@Judd515 
Yes, just remove names from elements then they won't be displayed on attributes.

<img width="534" alt="Screen Shot 2021-09-21 at 12 56 51" src="https://user-images.githubusercontent.com/90505831/134109490-ffb2a869-510f-42a6-96b7-e70acad7bbbe.png">
