### ISSUE TITLE
Generate specific layers

### ISSUE THREAD

**Issue by ghost** [HashLips/generative-art-opensource#189]
generative art opensource V3

i have race: male and I have 8 layers with 30 images. is it posible from my 8 layer select two or three layer and generate  images  from this specific layers? after chouse 3 diffecrent layer and generate from this layers.. How do I do that?
![tempsnip](https://user-images.githubusercontent.com/95852244/148450375-8c59fdeb-7945-4019-ad3b-04571070edbe.png)
I have all 8 layer in this Race Male..

**Comment by BBchG** [comment]
/* Comment */
