### ISSUE TITLE
Missing Background Color

### ISSUE THREAD

**Issue by lucamarial** [HashLips/generative-art-opensource#191]
Hello everyone,

I have a problem regarding my Background Layer:

Some of my generated images have a white background color even though I added colorful background images to my Background Layer, I set each image's weight to #100 and I set the variable `const background` to false.

The json file associated with the image shows an existing background layer, yet the image itself has a white background.

```JSON
  "image": "image.png",
  "external_url": "",
  "edition": 3,
  "attributes": [
    {
      "trait_type": "Background",
      "value": "Burly Wood"
    },
```

Does anyone know a solution to my problem?
I appreciate any help!

**Comment by djkaleb23** [comment]
Did you ever find a solution to this? I'm having the same problem.

**Comment by joshuadelgardo** [comment]
> Did you ever find a solution to this? I'm having the same problem.

The problem is you have saved one or more of the elements above the background layers with a white background, have another look at the files and resave as needed.

**Comment by djkaleb23** [comment]
Thanks just checked it and one of the layers had a background that was covering the bottom layer.
