### ISSUE TITLE
Program is not running

### ISSUE THREAD

**Issue by Ramirotorrese** [HashLips/generative-art-opensource#21]
Hi i am not sure what i am missing.. Any help will be really appreciated 
![image](https://user-images.githubusercontent.com/90022552/131955784-a1aa9dc4-4315-4de1-b69e-8da0b14401c9.png)

**Comment by EvilShaggz** [comment]
Did you run yarn add all

**Comment by Ramirotorrese** [comment]
yes,

**Comment by EvilShaggz** [comment]
Sorry dude i am a complete novice that is pretty much all i got.

**Comment by Ponda1** [comment]
The error says that canvas is not installed.
Try running npm install canvas.
That should fix the problem

**Comment by Ramirotorrese** [comment]
It worked. Awesome. thanks for the hlep
