### ISSUE TITLE
Running program issues 

### ISSUE THREAD

**Issue by Ramirotorrese** [HashLips/generative-art-opensource#28]
![image](https://user-images.githubusercontent.com/90022552/132084978-9efc5e4a-cc29-4278-8f39-c57e97c614ae.png)
Any help will be really appreciated

**Comment by Ponda1** [comment]
I believe this issue is the same as issue #22 so im just gonna paste my reply here.


This issue means something is wrong with the edition values in the config file. Check the edition values and rarityWeights and make sure they are correct. For example, if I wanna make 100 editions then startEditionFrom should be 1 and editionSize should be 100. The rarity weights could be something like (super_rare, 1, 10) , (rare, 11, 49) and (original 50,100).

**Comment by Ramirotorrese** [comment]
thanks @Ponda1     
i made those changes but still get this error now
![image](https://user-images.githubusercontent.com/90022552/132105310-1f3efa1f-c9c4-44b9-8a72-e30dacf021b2.png)

**Comment by Ramirotorrese** [comment]
Do you need to put special names to the different levels of rarity on the layers?

**Comment by Ponda1** [comment]
Again this error was ecountered in issue #33 which has now been closed. It means the generator is trying to find something which doesnt exist. I think the issue could be due to incorrect RarityPercentForLayer in the config file. Check the different rarity percentages and make sure they add up to 100. It could also mean that one of your layer folders is empty which the generator is trying to get an element from.

**Comment by Ramirotorrese** [comment]
@Ponda1  i made the changes you suggested , It worked once and it stop working :(. Not sure what it stopped working .

let rarityWeights = [
  addRarity('super_rare', 1, 10),
  addRarity('rare', 11, 49),
  addRarity('original', 50, 100)
];


const layers = [
  addLayer('background', { x: 0, y: 0 }, { width: width, height: height }),
  addLayer('body'), 
  addLayer('cheeks'), 
  addLayer('ears'), 
  addLayer('clothes'), 
  addLayer('mouth'), 
  addLayer('eyes'), 
  addLayer('mobility'), 
  addLayer('confetti'), 
  addLayer('glasses'), 
  addLayer('nose'), 
  addLayer('hats') 
];

addRarityPercentForLayer('super_rare', 'background', { 'super_rare': 10, 'rare': 40, 'original': 50 });
addRarityPercentForLayer('super_rare', 'body', { 'super_rare': 10, 'rare': 40, 'original': 50 });
addRarityPercentForLayer('super_rare', 'cheeks', { 'super_rare': 10, 'rare': 40, 'original': 50 });
addRarityPercentForLayer('super_rare', 'ears', { 'super_rare': 40, 'rare': 40, 'original': 20 });
addRarityPercentForLayer('super_rare', 'clothes', { 'super_rare': 10, 'rare': 40, 'original': 50 });
addRarityPercentForLayer('original', 'mouth', { 'super_rare': 10, 'rare': 30, 'original': 60 });
addRarityPercentForLayer('original', 'eyes', { 'super_rare': 10, 'rare': 30, 'original': 60 });
addRarityPercentForLayer('original', 'mobility', { 'super_rare': 50, 'rare': 40, 'original': 10 });
addRarityPercentForLayer('super_rare', 'confetti', { 'super_rare': 80, 'rare': 20, 'original': 0 });
addRarityPercentForLayer('rare', 'glasses', { 'super_rare': 20, 'rare': 70, 'original': 10 });
addRarityPercentForLayer('original', 'nose', { 'super_rare': 10, 'rare': 40, 'original': 50 });
addRarityPercentForLayer('super_rare', 'hats', { 'super_rare': 30, 'rare': 40, 'original': 30 });

**Comment by CryptoDynasty** [comment]
Did anyone ever figure out which sections you make changes to, so you can increase the creation amount? I made a change only to

// amount of NFTs to generate in edition
const editionSize = 50;

anything other than 10 results in  

let num = Math.floor(Math.random() * layer.elementIdsForRarity[_rarity].length); error

**Comment by elenderg** [comment]
Do this: 
```
var editionSize = 10000;
var TenPerCent= Math.round(editionSize / 10);
var TenPerCentPlusOne= Math.round(TenPerCent + 1);
var Half= Math.round(editionSize / 2);
var HalfPlusOne = Math.round(Half+ 1);
var TotalNFTAmount = Math.round(editionSize);
```

Don't forget toput this at the top of config.js file. Delete the `const editionSize` line.

**Comment by elenderg** [comment]
@CryptoDynasty  Do this: 
```
var editionSize = 10000;
var TenPerCent= Math.round(editionSize / 10);
var TenPerCentPlusOne= Math.round(TenPerCent + 1);
var Half= Math.round(editionSize / 2);
var HalfPlusOne = Math.round(Half+ 1);
var TotalNFTAmount = Math.round(editionSize);
```
and change `rarityWeights`  to
```
let rarityWeights = [
  addRarity('super_rare', 1, TenPerCent), // é um range
  addRarity('rare', TenPerCentPlusOne, Half),
  addRarity('original', HalfPlusOne , TotalNFTAmount )
```

Don't forget to put this at the top of config.js file. Delete the `const editionSize` line.
