### ISSUE TITLE
how to edit addRarityPercentForLayer to create images without a certain layer

### ISSUE THREAD

**Issue by Y-Ali** [HashLips/generative-art-opensource#36]
I'm trying to find a way to edit this part of the code to allow some images to be created that do **not** include any layers from my 'accessory' folder:

```
addRarityPercentForLayer('original', 'accessory', { 'super_rare': 10, 'rare': 30, 'original': 70 });
addRarityPercentForLayer('rare', 'accessory', { 'super_rare': 0, 'rare': 100, 'original': 0 });
addRarityPercentForLayer('super rare', 'accessory', { 'super_rare': 60, 'rare': 40, 'original': 0 });

```
Currently, if I run the code with the above; every single image that is created seems to have the accessory layer but I would want some images not to have this layer - any suggestions?

Thanks!

**Comment by EvilShaggz** [comment]
I just put a transparent image with none in that folder to fix it for me

**Comment by pehcastro** [comment]
> I just put a transparent image with none in that folder to fix it for me

I do this too, you can use the image as "no accessory.png" for metadata output, works fine.

**Comment by Y-Ali** [comment]
Thank you for this suggestion @EvilShaggz @pehcastro !
