### ISSUE TITLE
Baseimage uri

### ISSUE THREAD

**Issue by EvilShaggz** [HashLips/generative-art-opensource#47]
Hi everyone i am wanting to store my images and metadata on ipfs for persistence is there a way to make this program generate the baseimgeuri as an ipfs cid and store this in the metadata?

**Comment by beepboprobop** [comment]
Having this problem also

**Comment by Ponda1** [comment]
Since I am not an experienced coder I found an easy trick to do this. In the config file change the image value to something like "ipfslink" and generate the nfts. Once generated upload all the images onto ipfs BUT not the metadata and get the cid. At this point you have an ipfs link for the nfts. Open the generator, If youre using visual studio code (which I do), press ctrl+shift+ f and in the search box type ipfslink. Now in the replace box paste the ipfs link you got for the images and click replace for all files. This will replace the "ipfslink" in all metadata files with the new link. Now upload the metadata onto ipfs and now you have the baseimageuri with working metdata links ;)

**Comment by EvilShaggz** [comment]
Solid logic except the ipfs link is is individual to each png and is not a simple incremental 

Thanks ponda

**Comment by Ponda1** [comment]
@EvilShaggz you can upload the whole png folder theough gateways like pinata so they will be incremental ;)

**Comment by EvilShaggz** [comment]
Wait what are you serious?

Kind regards

Michael Cox

On 7 Sep 2021, at 12:45 pm, Ponda1 ***@***.***> wrote:

﻿

@EvilShaggz<https://github.com/EvilShaggz> you can upload the whole png folder theough gateways like pinata so they will be incremental ;)

**Comment by EvilShaggz** [comment]
Thats great news ponda now i have to figure out how to program a app to go through each json file and update the baseimageuri can you point me in the right direction?

**Comment by miguelmigs24** [comment]
You can actually do that by creating a folder on IPFS. That folder will have an unique CID then you can later add a "/image.png" to the end of the link and it will show you the image inside that folder. For example. You create a folder and you put an image called 'image.png' inside. Your link to that image will be : https://ipfs.io/ipfs/'FOLDERCID/image.png  
This works but has two problems: People can figure out which NFT's will correspond to each image before minting. You won't be able to ever edit those images too.

**Comment by EvilShaggz** [comment]
I don't seem to be able to get it to work this way every time I add a file it changes the CID and the CID for each image is unique no partenfilCID/imageName.png

> You can actually do that by creating a folder on IPFS. That folder will have an unique CID then you can later add a "/image.png" to the end of the link and it will show you the image inside that folder. For example. You create a folder and you put an image called 'image.png' inside. Your link to that image will be : https://ipfs.io/ipfs/'FOLDERCID/image.png
> This works but has two problems: People can figure out which NFT's will correspond to each image before minting. You won't be able to ever edit those images too.

**Comment by EvilShaggz** [comment]
every time i add a file to the ipfs folder I created it changes the folders hash so I can't use that as the baseimage uri am I missing something?

**Comment by miguelmigs24** [comment]
I just discovered that happened too and now I'm kinda stuck. I don't wanna
be paying for a server forever . Sorry for misleading you , I thought the
hash didn't change

A terça, 7/09/2021, 13:09, EvilShaggz ***@***.***> escreveu:

**Comment by EvilShaggz** [comment]
all Good i appreciate the help anyway, 

back to learning fumbling my way through coding videos -_-

**Comment by Ponda1** [comment]
@EvilShaggz did my comments not give you the solution? I deleted them because not only is this issue out of the scope of this repository but also because id rather have someone experienced give a "proper" coding solution to this problem rather than using my "trick".

**Comment by EvilShaggz** [comment]
Hey ponda no it didnt really fix the issue and is this really out of scope conidering the code has baseimgaeuri in it happy to close and look elsewhere if others agree
