### ISSUE TITLE
What am I missing? :-(

### ISSUE THREAD

**Issue by cupcakes99** [HashLips/generative-art-opensource#52]
Error: Cannot find module 'C:\Users\User\...\generative-art-opensource-3\index.js' 
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

I've tried:
npm install
npm install truffle -g
npm install truffle -p
yarn add all

**Comment by Snurlz** [comment]
Npm install -i canvas

**Comment by stringcheeseslut** [comment]
> Npm install -i canvas

Where do you find this? I can't seem to find it online anywhere

**Comment by cupcakes99** [comment]
> > Npm install -i canvas
> 
> Where do you find this? I can't seem to find it online anywhere

Just type it into the terminal 😊

**Comment by EddieKane** [comment]
I have tried everything not even npm install -i canvas is working. im stuck and havent even started lmao

**Comment by roxannegerber** [comment]
What is the error? I also had to enable the writing of scripts by setting
my execution policy to unrestricted (Windows)
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/set-executionpolicy?view=powershell-7.1

**Comment by EddieKane** [comment]
PS C:\Users\Trapfather\Desktop\generative-art-opensource-main> npm install
npm : The term 'npm' is not recognized as the name of a cmdlet, function, script file, or 
operable program. Check the spelling of the name, or if a path was included, verify that the     
path is correct and try again.
At line:1 char:1
+ npm install
+ ~~~
    + CategoryInfo          : ObjectNotFound: (npm:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
