### ISSUE TITLE
while loop break

### ISSUE THREAD

**Issue by jayvi** [HashLips/generative-art-opensource#6]
when set :
const startEditionFrom = 1;
const endEditionAt = 25;
const editionSize = 25;
const rarityWeights = [
  {
    value: "super_rare",
    from: 1,
    to: 2,
  },
  {
    value: "rare",
    from: 3, // this should start from 3
    to: 5,
  },
  {
    value: "original",
    from: 6, // this should start from 6
    to: editionSize,
  },
];

or default one that are in repo when hits 19th element the code bug and stop there so when bug comes I get 18 images without metadata cause breaking the loop to stop it. any help with this ? (plus saw one more guy have same issue like me :( )

**Comment by jayvi** [comment]
can you add something like this

var arrayShuffle = function(array) {
  for ( var i = 0, length = array.length, swap = 0, temp = ''; i < length; i++ ) {
     swap        = Math.floor(Math.random() * (i + 1));
     temp        = array[swap];
     array[swap] = array[i];
     array[i]    = temp;
  }
  return array;
};

var percentageChance = function(values, chances) {
  for ( var i = 0, pool = []; i < chances.length; i++ ) {
     for ( var i2 = 0; i2 < chances[i]; i2++ ) {
        pool.push(i);
     }
  }
  return values[arrayShuffle(pool)['0']];
};

for ( var i = 0; i < 20; i++ ) {
  console.log(percentageChance([
"original",
"rare",
   "super rare" 
   "extra rare" ], 
[30,34, 35, 1]);); // this numbers represent the % of each key to be used in array generation
}

**Comment by HashLips** [comment]
> when set :
> const startEditionFrom = 1;
> const endEditionAt = 25;
> const editionSize = 25;
> const rarityWeights = [
> {
> value: "super_rare",
> from: 1,
> to: 2,
> },
> {
> value: "rare",
> from: 3, // this should start from 3
> to: 5,
> },
> {
> value: "original",
> from: 6, // this should start from 6
> to: editionSize,
> },
> ];
> 
> or default one that are in repo when hits 19th element the code bug and stop there so when bug comes I get 18 images without metadata cause breaking the loop to stop it. any help with this ? (plus saw one more guy have same issue like me :( )

I made changes to you above example, also make sure you have enough images to create unique DNA.

**Comment by jayvi** [comment]
thanks mate appreciate it and in youtube answers also 🥂

**Comment by jayvi** [comment]
any chance to advice me about https://github.com/HashLips/generative-art-opensource/issues/27
