### ISSUE TITLE
Problem with increasing edition size to anything other than 10

### ISSUE THREAD

**Issue by CryptoDynasty** [HashLips/generative-art-opensource#62]
Did anyone ever figure out which sections you make changes to, so you can increase the creation amount? I made a change only to

// amount of NFTs to generate in edition
const editionSize = 50;

anything other than 10 results in

let num = Math.floor(Math.random() * layer.elementIdsForRarity[_rarity].length); error

If I change
// amount of NFTs to generate in edition
const editionSize = 50;

to

// amount of NFTs to generate in edition
const editionSize = 10;

without changing any other code it works fine.

**Comment by Ponda1** [comment]
Along with changing the edition size you have to change the values of the number of super_rare , rare and original editions made to match however many editions you are making.

**Comment by chitownprince** [comment]
I am running into the same issue, even after following the above linked thread. My const editionSize =20 and the rarity weights are set to: 

let rarityWeights = [
  addRarity('super_rare', 18, 20),
  addRarity('rare', 12, 18),
  addRarity('original', 1, 12)

I also tried with the below but still couldn't get the script to generate more than 10. 

let rarityWeights = [
  addRarity('super_rare', 19, 20),
  addRarity('rare', 13, 18),
  addRarity('original', 1, 12)

**Comment by CryptoDynasty** [comment]
Thanks!, Ponda!
