### ISSUE TITLE
how can i make JSON file for each PNG?

### ISSUE THREAD

**Issue by cryptouzi** [HashLips/generative-art-opensource#63]
how can i change it, to where i can make a JSON file along with a PNG for each NFT?

**Comment by Ponda1** [comment]
Download the v3 branch. In the index file there are two instances of code which mention saveMetadataSingleFile. Copy and paste both pieces of code into the index file of whichever branch you are using.

**Comment by cryptouzi** [comment]
tried it but it stops after 1 creation

**Comment by Ponda1** [comment]
I have no idea then, I did exactly the same thing and it worked for me. Are you sure you did it correctly? I would post the code here but it would be too long and im on my phone rn :/

**Comment by cryptouzi** [comment]
Yes i copied the 2 codes which mention saveMetaDataSingleFile. I thought it was going to work but it stoped after 1 JSON and 1 PNG

**Comment by cryptouzi** [comment]
I finally got it to work. Now JSON is being made with png BUTTTT json file is showing "name, edition, etc." but now showing the actual backgrounds details

**Comment by cryptouzi** [comment]
Sorry simple fix lol forgot to add "attributesList" thanks for all your help! I could not have done it myself

**Comment by Ponda1** [comment]
Glad to hear that! You can close this issue then.

**Comment by bladeninja888** [comment]
still not able to add the second line of code please help:

https://github.com/HashLips/generative-art-opensource/issues/91

**Comment by bladeninja888** [comment]
> attributesList

can you explain this step of code bro and where to put attributelist?

**Comment by bladeninja888** [comment]
> Sorry simple fix lol forgot to add "attributesList" thanks for all your help! I could not have done it myself

can you explain more please? I'm stuck here,

Every Json file I get only has name but no traits: #98

**Comment by gcod** [comment]
This works with current main
[index.zip](https://github.com/HashLips/generative-art-opensource/files/7247185/index.zip)
