### ISSUE TITLE
Error: ENOENT: no such file or directory, scandir

### ISSUE THREAD

**Issue by Th3HotDog** [HashLips/generative-art-opensource#72]
Keep getting this error when I run the code using "node index.js".  I'm not sure what to do here. I tried to look for a path but didn't really see much. I'm also really new to coding so. Any help would be much appreciated. 
I have made sure the folders had a, "orignal", "rare", and super_rare" sub directories with images inside. The code runs fine obviously without any edits. 

The only thing I have changed in the code is the editionSize to 10 and edited the code to read:

// create required layers
// for each layer, call 'addLayer' with the id and optionally the positioning and size
// the id would be the name of the folder in your input directory, e.g. 'ball' for ./input/ball
const layers = [
  addLayer('Body', { x: 0, y: 0 }, { width: width, height: height }),
  addLayer('Claws'),
  addLayer('Coat Color'),
  addLayer('Eyes')
];

// provide any specific percentages that are required for a given layer and rarity level
// all provided options are used based on their percentage values to decide which layer to select from
addRarityPercentForLayer('super_rare', 'Body', { 'super_rare': 33, 'rare': 33, 'original': 33 });
addRarityPercentForLayer('super_rare', 'Claws', { 'super_rare': 50, 'rare': 25, 'original': 25 });
addRarityPercentForLayer('original', 'Claws', { 'super_rare': 50, 'rare': 25, 'original': 25 });
 

![issu](https://user-images.githubusercontent.com/90287413/132414995-c945f946-737d-4623-9319-64810032373c.jpg)

**Comment by Ponda1** [comment]
After changing the editionSize to 10 did you change the values of rarities as well? Refer to issue #62 for more info. Also make sure the names of the layers and folders match. You couldve missed an upper case letter or something

**Comment by Th3HotDog** [comment]
So here are my layers, they seem to check out to me.

![image](https://user-images.githubusercontent.com/90287413/132417411-e1556813-88aa-44b0-b4c8-d3a5ae4201f4.png)

And my rarity issue I think is fine too. 
![image](https://user-images.githubusercontent.com/90287413/132417505-6fa3473e-60bd-451e-82ec-219935480930.png)

**Comment by lordexe** [comment]
Same problem

**Comment by lordexe** [comment]
Found anything yet?

**Comment by Th3HotDog** [comment]
Nope please let me know if you do. I've been looking and nothing...

**Comment by 00Luis** [comment]
did you solve it?
