### ISSUE TITLE
Output Node.js No images created

### ISSUE THREAD

**Issue by jerrodjam** [HashLips/generative-art-opensource#76]
I get the following, i know it is simple fix as everything is running. Just s hint of guidance would be appreciated.

creating NFT 9 of 10
- rarity: rare
- dna: 02-05-01-01-01-01
- metadata: {"dna":"020501010101","name":"#9","description":"This is an NFT made by the coolest generative code.","image":"https://hashlips/nft/9","edition":9,"date":1631073164541,"attributes":[{"name":"green eye ball rare"},{"name":"purple small rare"},{"name":"medium rare"},{"name":"shapes rare"},{"name":"tilted bottom rare"},{"name":"low top rare"}]}
- edition 9 created.

**Comment by EvilShaggz** [comment]
That does not appear to be an error

**Comment by jerrodjam** [comment]
Okay perfect, this is good. I'm assuming to achieve created images is a completely separate. I was under impression the terminal would show images.

**Comment by EvilShaggz** [comment]
No they appear in the output folder

**Comment by jerrodjam** [comment]
You my friend, have helped. Do you mind if I ask a few more questions here?
I am in config.js
If i edit the NFTs to lets say 100, what do i have to edit to ensure this goes through?

**Comment by EvilShaggz** [comment]
Probably the rarity weight values to go up to 100 and ensure there is enough possible combinations of layers to produce that

**Comment by jerrodjam** [comment]
right, okay i have enough confidence now to fiddle around with this. I just didnt know how to get original to run and you helped thank you.

**Comment by EvilShaggz** [comment]
If you are going to fiddle i just duplicate the whole folder and go ham knowing i have a working one to refer to
