### ISSUE TITLE
Made my 1st nft collection!

### ISSUE THREAD

**Issue by Ponda1** [HashLips/generative-art-opensource#88]
This isnt an issue but thanks to HashLips and you guys ive finally made my 1st NFT collection of 3333 Precious Pandas. I would appreciate it if you guys can check it out !
www.preciouspandas.42web.io

**Comment by tradermoore** [comment]
Congrats, looks awesome!!  I suppose you hooked yours up to Eth network instead of through Poly?  Also, wondering if you used main branch or v3?  Been following some of your work through the issues and impressed at your efforts.

**Comment by Diddi81Ma** [comment]
> This isnt an issue but thanks to HashLips and you guys ive finally made my 1st NFT collection of 3333 Precious Pandas. I would appreciate it if you guys can check it out !
> 
> www.preciouspandas.42web.io

**Comment by KGalaffu** [comment]
Congratulations, and long live the precious Panda! 

Would it be possible to ask for your help regarding IPFS ?

**Comment by Ponda1** [comment]
I absolutely love the support guys couldnt be happier. Just ask me anything and I'll help you out as ive always tried to on this github. @tradermoore yeah I hooked it up to ethereum and it was really expensive! @KGalaffu what help do you need?

**Comment by KGalaffu** [comment]
Do you have a discord? It would be easier to tell you my problem there ^^
 I'll leave you mine here : Fufette#2276

**Comment by tradermoore** [comment]
@Ponda1 Awesome! Did you have to add in the code to create individual metadata per edition on main branch?  

Also, did you just leave the NFTs in their order generated, ie first 2000 or so are common, next 800 rare, etc??

**Comment by KGalaffu** [comment]
> @Ponda1 Awesome! Did you have to add in the code to create individual metadata per edition on main branch?
> 
> Also, did you just leave the NFTs in their order generated, ie first 2000 or so are common, next 800 rare, etc??

Haha I see that we ask ourselves the same questions

**Comment by Ponda1** [comment]
I dont really use discord but I'll make a server. https://discord.gg/fCSbSwkG
We can chat there

**Comment by Ponda1** [comment]
@tradermoore yeah I made individual metadata for each file. You have to do that to get the attributes made properly.

**Comment by tradermoore** [comment]
Awesome, thanks @Ponda1 I'll update my code to do the same next.

**Comment by bladeninja888** [comment]
@Ponda1 Ponda congrats! Can you share your Panda NFT code in a repository? That will be much appreciated and help the community to figure out some of the issues. 

Thank you!
